name: CI
on: [push]

env:
  DOCKER_IMAGE_VERSION: master-105004115
  DEFAULT_DOCKER_IMAGE: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115
  DOCKER_OPTIONS: --mount type=bind,source=$(pwd),destination=/home/bst-plugins-container --workdir=/home/bst-plugins-container

jobs:
        #  simple-jobs: 
        #    name: ${{matrix.task.name}}
        #    runs-on: ubuntu-latest
        #    container:
        #      image: ${{matrix.image}}
        #      env: ${{matrix.task.docker-env}}
        #
        #    strategy:
        #      fail-fast: false
        #      matrix:
        #        image:
        #          - registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115
        #        task:
        #          - name: format-check
        #            commands: tox -e format-check
        #            docker-env: {}
        #          - name: lint
        #            commands: tox -e lint,rst-lint
        #            docker-env: {}
        #          - name: docs 
        #            commands: |
        #              tox
        #              mkdir artifact
        #              sudo mv doc/build/html artifact/public
        #            docker-env:
        #              DOCKER_HOST: tcp://docker:2375/
        #              PY_COLORS: 1
        #              PYTEST_ADDOPTS: '--color=yes'
        #              DOCKER_TLS_CERTDIR: ""
        #              TOXENV: docs
        #            artifact-name: public
        #            artifact-path: artifact
        #
        #    steps: 
        #      - uses: actions/checkout@v2
        #      - name: ${{matrix.task.name}}
        #        run: ${{matrix.task.commands}}
        #      - if: ${{matrix.task.artifact-name}}
        #        uses: actions/upload-artifact@v1
        #        with:
        #          name: ${{matrix.task.artifact-name}}
        #          path: ${{matrix.task.artifact-path}}
        #
  py-tests:
    name: tests-py37
    runs-on: ubuntu-latest
      #    container:
      #      image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115
      #      env: 
      #        DOCKER_HOST: tcp://docker:2375/
      #        PY_COLORS: 1
      #        PYTEST_ADDOPTS: '--color=yes'
      #        DOCKER_TLS_CERTDIR: ""
      #        TOXENV: py37
      #    services:
      #      docker:dind:
      #        image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - name: tests-py37
        run: |
          docker run --privileged --rm -p 12375:2375 -e DOCKER_TLS_CERTDIR="" docker:dind &
          docker run \
            --network=host --rm \
            --mount type=bind,source=$(pwd),destination=/home/root \
            --workdir=/home/root \
            -e DOCKER_HOST=tcp://localhost:12375/ \
            -e DOCKER_TLS_CERTDIR="" \
            -e PY_COLORS=1 \
            -e PYTEST_ADDOPTS='--color=yes' \
            -e TOXENV=py37 \
            registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-master-105004115 \
            tox -- --docker
